#templates.py
import textwrap

BPF_TEMPLATE = textwrap.dedent("""
#define __TARGET_ARCH_x86
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

#include "common_event.h"

char LICENSE[] SEC("license") = "Dual BSD/GPL";

struct {{
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
}} events SEC(".maps");

struct {{
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 10240);
    __type(key, __u64);
    __type(value, __u8);
}} cgroup_map SEC(".maps");
    
SEC("tracepoint/syscalls/sys_enter_{name}")
int trace_{name}(struct trace_event_raw_sys_enter *ctx) {{
    char comm[16];
    bpf_get_current_comm(&comm, sizeof(comm));

    /* [변경] 기존 comm 필터 로직을 Cgroup ID 필터로 교체 */
    __u64 cgroup_id = bpf_get_current_cgroup_id();
    __u8 *should_trace = bpf_map_lookup_elem(&cgroup_map, &cgroup_id);

    // 맵에 없으면 (NULL) 즉시 종료 (필터링)
    if (!should_trace) {{
        return 0;
    }}

    /* 이하 eBPF 이벤트 생성 코드 계속… */
    struct event_t *e = bpf_ringbuf_reserve(&events, sizeof(*e), 0);
    if (!e)
        return 0;
    e->pid   = bpf_get_current_pid_tgid() >> 32;
    e->type  = EVT_{NAME};
    e->ts_ns = bpf_ktime_get_ns();
    {bindings}
    bpf_ringbuf_submit(e, 0);
    return 0;
}}
""")

MAKEFILE = textwrap.dedent("""
# Auto-generated by generate_bpf.py
BPFTOOL ?= bpftool
CC      = clang
#CFLAGS  := -O2 -g -Wall -Werror -target bpf -I. -Iinclude
LLVM_SYSROOT := $(shell $(CC) --print-resource-dir)/../..
KERNEL_SRCDIR ?= /usr/src/linux-headers-$(shell uname -r)

CFLAGS := -O2 -g -Wall -Werror -target bpf -nostdinc -isystem /usr/include -isystem $(LLVM_SYSROOT)/include -isystem $(LLVM_SYSROOT)/../lib/clang/*/include  -Iinclude -I. -I$(KERNEL_SRCDIR)/tools/lib/bpf/include
                           
# 모든 bpf 오브젝트와 스켈레톤 헤더를 빌드
TARGETS := {targets}
OBJECTS := $(addprefix bpf/,$(addsuffix _monitor.bpf.o, $(TARGETS)))
SKELETONS := $(addprefix bpf/,$(addsuffix _monitor.skel.h, $(TARGETS)))

all: $(OBJECTS) $(SKELETONS) monitor_loader
                          
# 패턴 규칙: _name_monitor.bpf.c -> _name_monitor.bpf.o
bpf/%_monitor.bpf.o: bpf/%_monitor.bpf.c include/common_event.h
	$(CC) $(CFLAGS) -Iinclude -c $< -o $@

# 패턴 규칙: .bpf.o -> .skel.h
bpf/%_monitor.skel.h: bpf/%_monitor.bpf.o
	$(BPFTOOL) gen skeleton $< > $@

monitor_loader: monitor_loader.c
	gcc -o $@ $< \
	-Iinclude \
	-I. \
	-I$(LLVM_SYSROOT)/include \
	-I$(KERNEL_SRCDIR)/tools/lib/bpf/include \
	-lbpf -lrdkafka -lpthread

clean:
	rm -f ./bpf/*.bpf.c ./bpf/*.bpf.o ./bpf/*.skel.h monitor_loader monitor_loader.c
""")

LOADER_TEMPLATE = textwrap.dedent("""
/* [추가] open_memstream을 위해 _GNU_SOURCE를 최상단에 추가 */
#define _GNU_SOURCE
/* [유지] nftw와 FTW_PHYS를 위해 _XOPEN_SOURCE 500 추가 */
#define _XOPEN_SOURCE 500
       
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <bpf/libbpf.h>
#include <librdkafka/rdkafka.h>       //***********KAFKA*************
#include <pthread.h>      /* [추가] */
#include <ftw.h>          /* [추가] */
#include <errno.h>        /* [추가] */
#include <sys/stat.h>     /* [추가] */
#include <bpf/bpf.h>      /* [추가] BPF_ANY */
#include "include/common_event_user.h"
{includes} 
// bpf 모니터링 스켈레톤 헤더들 생성위치 조정필요

static volatile bool running = true;
static rd_kafka_t *rk;            //***********KAFKA*************
static rd_kafka_topic_t *rkt;     //***********KAFKA*************
static int g_map_fds[{num_syscalls}] = {{{num_0f_minus1s}}}; 
static const char *event_type_str[] = {{
{enum_strings}
    }};
                                           

void sig_handler(int sig) {{
    running = false;
}}


//***********KAFKA*************                                  

// IMPROVEMENT: Kafka delivery report callback
static void dr_msg_cb(rd_kafka_t *rk, const rd_kafka_message_t *rkmessage, void *opaque) {{
    if (rkmessage->err) {{
        fprintf(stderr, " Message delivery failed: %s\\n", rd_kafka_err2str(rkmessage->err));
    }} else{{fprintf(stderr, " Message delivered to topic %s [%d] at offset %lld\\n",}}
}}

static void kafka_init() {{
    char errstr[512];
    rd_kafka_conf_t *conf = rd_kafka_conf_new(); //설정 객체 생성

    //환경변수 로드
    const char* kafka_topic = getenv("KAFKA_TOPIC");
    if (!kafka_topic) {{ kafka_topic = "syscall_events"; }}
    const char *kafka_bootstrap = getenv("KAFKA_BOOTSTRAP_SERVERS");
    if (!kafka_bootstrap) {{ kafka_bootstrap = "my-cluster-kafka-bootstrap.kafka.svc:9092"; }}

    // rd_kafka_conf_set 설정 객체에 부트스트랩 서버 설정입력
    // conf : 설정 객체
    // "bootstrap.servers" : 설정 키 <- 뭐임?
    // kafka_bootstrap : 설정 값
    // errstr, sizeof(errstr) : 오류 발생 시 오류 메시지 저장 버퍼 
    if (rd_kafka_conf_set(conf, "bootstrap.servers", kafka_bootstrap, errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) {{
        fprintf(stderr, "%s\\n", errstr);
        exit(1);
    }}  
                                  
    //전송완료 콜백함수 dr_msg_cb 등록
    rd_kafka_conf_set_dr_msg_cb(conf, dr_msg_cb);

    //설정객체 conf를 사용하여 프로듀서 객체 생성, RD_KAFKA_PRODUCER 타입으로 지정
    //프로듀서 객체가 정확히 뭔데? : 메시지를 카프카 클러스터로 보내는 역할
    rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
    if (!rk) {{
        fprintf(stderr, "Failed to create new producer: %s\\n", errstr);
        exit(1);
    }}
                                  
    //토픽 객체 생성
    //토픽 객체 : 메시지를 보낼 특정 카프카 토픽을 지정
    rkt = rd_kafka_topic_new(rk, kafka_topic, NULL);
    if (!rkt) {{
        fprintf(stderr, "Failed to create new topic : %s\\n", errstr);
        exit(1);
    }}
}}

static void kafka_send(const char* buffer, size_t len) {{
    //빈 버퍼 또는 길이 0인 경우 오류처리
    if (!buffer || len == 0) return;

    //여까진 정상적으로 찍히는거확인 ( 아래 주석 풀면 메세지 존나나옴)                            
    //fprintf(stderr,"debug Kafka_send\\n");
                                  
    // rd_kafka_produce(
    // rkt : 토픽 객체 지정
    // RD_KAFKA_PARTITION_UA : 파티션 자동 할당
    // RD_KAFKA_MSG_F_COPY : 메시지 데이터를 내부적으로 복사
    // (void*)buffer : 전송할 메시지 데이터
    // len : 메시지 길이
    // NULL, 0 : 키 없음
    // NULL : 추가 옵션 없음
    // )
    rd_kafka_produce(rkt, RD_KAFKA_PARTITION_UA, RD_KAFKA_MSG_F_COPY, (void*)buffer, len, NULL, 0, NULL);
    // Poll for delivery reports (and other events).
                                  
    //위의 프로듀스로 생성된 메세지를 네트워크를 통해 실제로 전송
    //결과는 dr_msg_cb 콜백함수로 비동기적으로 전달
    rd_kafka_poll(rk, 0);
                                  
    //printf("%s\\n", buffer);
}}

/* [추가] Cgroup 스캔 콜백 함수 (PoC 로직) */
static int dir_scan_callback(const char *fpath, const struct stat *sb, int typeflag, struct FTW *ftwbuf) {{
    if (g_map_fds[0] < 0) return -1; // 맵이 준비되지 않음

    if (typeflag == FTW_D) {{
        if (strstr(fpath, "kubepods") || strstr(fpath, "docker-")) {{
            __u64 cgroup_id = sb->st_ino;
            __u8 value = 1;

            /* [수정] 5개의 맵을 모두 순회하며 업데이트 */
            for (int i = 0; i < {num_syscalls}; i++) {{
                if (g_map_fds[i] < 0) continue; // 유효한 FD인지 확인
                
                // [수정] g_map_fds[i] (배열 요소)를 전달
                if (bpf_map_update_elem(g_map_fds[i], &cgroup_id, &value, BPF_ANY) != 0) {{
                    // fprintf(stderr, "Failed to update map[%d] for cgroup %s (ID: %llu): %s\\n", i, fpath, cgroup_id, strerror(errno));
                }}
            }}
        }}
    }}
    return 0; // 계속 스캔
}}
                                  
/* [추가] Cgroup 스캐너 스레드 함수 (PoC 로직) */
void *scanner_thread(void *arg) {{
    if (g_map_fds[0] < 0) {{
        fprintf(stderr, "Scanner thread received invalid map FD\\n");
        return NULL;
    }}

    /* [수정] 기존 'running' 전역 변수를 사용  */
    while (running) {{ 
        // printf("Scanning /sys/fs/cgroup...\\n");

        if (nftw("/sys/fs/cgroup", dir_scan_callback, 20, FTW_PHYS) == -1) {{
            fprintf(stderr, "Cgroup scan failed: %s\\n", strerror(errno));
        }}

        sleep(5); // 5초 대기
    }}
    return NULL;
}}

static void fprint_json_escaped_str(FILE *f, const char *s) {{
    fputc('"', f);
    if (!s) {{
        fputc('"', f);
        return;
    }}
    while (*s) {{
        switch (*s) {{
            case '"': fprintf(f, "\\""); break;
            case '\\\\': fprintf(f, "\\\\"); break;
            case '\\b': fprintf(f, "\\\\b\"); break;
            case '\\f': fprintf(f, "\\\\f\"); break;
            case '\\n': fprintf(f, "\\\\n\"); break;
            case '\\r': fprintf(f, "\\\\r\"); break;
            case '\\t': fprintf(f, "\\\\t\"); break;                                       
            default:
                if ((unsigned char)*s < 0x20) {{
                    fprintf(f, "\\\\u%04x", (unsigned char)*s);
                }} else {{
                    fputc(*s, f);
                }}
                break;
        }}
        s++;
    }}
    fputc('"', f);
}}

// 링버퍼로부터 수신한 데이터 JSON 직렬화 및 전송
static void serialize_and_send(const struct event_t *e) {{
    char *buf = NULL;
    size_t size = 0;
    FILE *f = open_memstream(&buf, &size);
    if (!f) return;

    fprintf(f, "{{\\"type\\":\\"%s\\",\\"pid\\":%u,\\"ts\\":%llu", event_type_str[e->type], e->pid, e->ts_ns);

    // Event-specific data
    switch (e->type) {{
{event_cases}
    default:
        break;
    }}

    fprintf(f, "}}");
    fclose(f);

                                  
    //stdout_send(buf, size) 하면 콘솔에 출력 됨, buf에는 정상적인 json 문자열이 들어있음
    //***********KAFKA*************
    //여기 디버깅코드 넣으니까 반복되긴함
    kafka_send(buf, size);
    free(buf);
}}

// 콜백 함수: 링버퍼에서 이벤트 수신 시 호출되는 함수
static int on_event(void *ctx, void *data, size_t size) {{
    serialize_and_send((const struct event_t *)data);
    return 0;
}}

int main() {{
    bool scanner_started = false;
    signal(SIGINT, sig_handler);
    signal(SIGTERM, sig_handler);
        
//***********KAFKA*************
   kafka_init();

fprintf(stderr, "debug 1\\n");
    {skeletons}
fprintf(stderr, "debug 2\\n");
    struct ring_buffer *rbs[{num_syscalls}];
fprintf(stderr, "debug 3\\n");
    {attaches}

fprintf(stderr, "debug 4\\n");
    /* [추가] 스캐너 스레드 초기화 (code_generator.py에서 생성) */
    {cgroup_scanner_init}

fprintf(stderr, "debug 5\\n");               
    //ring_buffer_new : 각 시스콜에 대해 링버퍼 생성하고, 콜백함수등록(on_event)
    {rbs_initializers}
fprintf(stderr, "debug 6\\n");
    for (int i = 0; i < {num_syscalls}; i++) {{
    if (!rbs[i]) {{
        fprintf(stderr, "Failed to create ring buffer for syscall %d\\n", i);
        goto cleanup;
        }}
    }}
fprintf(stderr, "debug 7\\n");


   printf("Monitoring syscalls... Press Ctrl+C to exit.\\n\\n");
    fprintf(stderr, "debug 8\\n");  
    while (running) {{
        for (int i = 0; i < {num_syscalls}; i++) {{
            // non-blocking으로 모든 버퍼를 빠르게 순회하기 위해 timeout을 짧게 설정 (예: 1ms)
            //ring_buffer_poll : 이벤트가 있으면 rbs[i]의 콜백 함수(on_event)를 호출
            if (ring_buffer__poll(rbs[i], 1) < 0) {{
                fprintf(stderr, "Error polling ring buffer %d\\n", i);
                break; // 에러 발생 시 외부 루프도 종료
            }}
        }}
        rd_kafka_poll(rk, 0);
        // CPU 사용을 줄이기 위해 잠시 대기
        usleep(1000);
    }}

cleanup:
         fprintf(stderr, "debug cleanup\\n");                         
    /* [추가] 스캐너 스레드 종료 대기 */
    {cgroup_scanner_join}
                                  
    for (int i = 0; i < {num_syscalls}; i++) {{
        ring_buffer__free(rbs[i]);
    }}
    {destroys}
    fprintf(stderr, "\\nFlushing final Kafka messages...\\n");
   //***********KAFKA*************
    rd_kafka_flush(rk, 10 * 1000); // Wait for max 10 seconds
    rd_kafka_topic_destroy(rkt);
    rd_kafka_destroy(rk);
    printf("Cleaned up resources.\\n");
    return 0;
}}
""")

BPF_HEADER = textwrap.dedent("""
//common_event.h
#pragma once
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>                      
                    
                             
    // IMPROVEMENT: Increased max string length for paths, etc.
    // This is a hard limit; longer strings will be truncated.
    #define MAX_STR_LEN 1024

enum event_type {{
    {enum_entries}
        EVT_MAX,
    }};

    
{struct_definitions}

struct event_t {{
        __u32 pid;
        enum event_type type;
        __u64 ts_ns;
        union {{
    {union_entries}
        }} data;
    }};
    """)

USER_HEADER = textwrap.dedent("""
//common_event_user.h
#pragma once

/* 1) 필수 헤더 */
#include <stdint.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <linux/keyctl.h>
#include <sys/capability.h>
#include <aio.h>
#include <mqueue.h>

/* 2) 축약형 정수 타입 */
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t  u8;
typedef  int64_t s64;
typedef  int32_t s32;
typedef  int16_t s16;
typedef   int8_t s8;

/* 3) uapi 헤더에 없는, 커널 전용 타입 매핑 */
/*    이미 정의된 표준 타입은 건드리지 않습니다. */
#ifndef umode_t
typedef mode_t             umode_t;           /* 파일 모드 */
#endif

#ifndef __kernel_dev_t
typedef dev_t              __kernel_dev_t;    /* 커널 dev_t */
#endif

#ifndef __kernel_loff_t
typedef long long          __kernel_loff_t;
#endif

#ifndef __kernel_time64_t
typedef long long          __kernel_time64_t;
#endif

#ifndef __kernel_clockid_t
typedef int                __kernel_clockid_t;
#endif

#ifndef __kernel_timer_t
typedef int                __kernel_timer_t;
#endif

#ifndef __kernel_uid32_t
typedef uid_t              __kernel_uid32_t;
#endif

#ifndef __kernel_gid32_t
typedef gid_t              __kernel_gid32_t;
#endif

#ifndef __kernel_size_t
typedef size_t             __kernel_size_t;
#endif

#ifndef __kernel_ssize_t
typedef ssize_t            __kernel_ssize_t;
#endif

#ifndef __kernel_pid_t
typedef pid_t              __kernel_pid_t;
#endif

#ifndef key_serial_t
typedef int                key_serial_t;
#endif

#ifndef aio_context_t
typedef unsigned long      aio_context_t;
#endif
   
                    
                             
    // IMPROVEMENT: Increased max string length for paths, etc.
    // This is a hard limit; longer strings will be truncated.
    #define MAX_STR_LEN 1024

    enum event_type {{
    {enum_entries}
        EVT_MAX,
    }};

    
    {struct_definitions}

    struct event_t {{
        __u32 pid;
        enum event_type type;
        __u64 ts_ns;
        union {{
    {union_entries}
        }} data;
    }};
    """)

STRUCT_TMPL = textwrap.dedent("""
    struct {name}_event_t {{
    {fields}
    }};
""")